{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes_agent.fullname" . }}
  labels: {{- include "kubernetes_agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes_agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubernetes_agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
